### ISSUE TITLE
Restructuring

### ISSUE THREAD

**Issue by jamalv** [teamforus/api.forus.io-ethereum#1]
Would it be possible to have a poc1 branch for @martijndoornik’s version of the platform, to keep the master branch clean for the new (in progress) version of forus.io? 

Also it would be nice to have martijns original commits if that is still possible

**Comment by maxvisser** [comment]
Do you know if this is the same version as in root of this directory?
https://github.com/teamforus/research-and-development/tree/poa001-demo-18-12-2017/demo003-platform

**Comment by jamalv** [comment]
I don't have write access here, could you assign @martijndoornik?

**Comment by maxvisser** [comment]
I renamed master to develop to make it feel like a development project instead of a finished product.

**Comment by jamalv** [comment]
@martijndoornik, where do you think this platform is best located? In this repo: api.forus.io-ethereum for example in a POC1/Prototype/Demo branch, or in research-and-development?

**Comment by jamalv** [comment]
it's in research and development, so this repo can be cleaned to prepare for the next version

**Comment by maxvisser** [comment]
added @martijndoornik 's two branches of https://github.com/martijndoornik/platform-forus-concept to this repo
